info:
  contact: {}
paths:
  /user/register:
    get:
      consumes:
      - application/json
      description: 用户注册
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 注册接口
      tags:
      - example
swagger: "2.0"
